plugins {
    id 'java'
    id 'com.vanniktech.maven.publish' version '0.34.0'
}

def getGitRef() {
    try {
        final def ref = providers.exec {
            commandLine 'git', 'rev-parse', '--short', 'HEAD'
            ignoreExitValue = true
        }.standardOutput.asText.get().trim()
        return ref.isEmpty() ? 'unknown' : ref
    } catch (final Throwable ignored) {
        return 'unknown'
    }
}

version = "${semver}+${getGitRef()}"
group = 'li.cil.ceres'

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    mavenCentral()
}

dependencies {
    compileOnly 'org.jetbrains:annotations:23.0.0'
    compileOnly 'com.google.code.findbugs:jsr305:3.0.2'

    implementation 'org.ow2.asm:asm-commons:9.10.1'
    implementation 'org.ow2.asm:asm:9.10.1'

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.8.2'
}

tasks.withType(AbstractArchiveTask).configureEach {
    archiveVersion = semver
}

mavenPublishing {
    publishToMavenCentral()
    if (providers.gradleProperty('signingInMemoryKey').present) {
        signAllPublications()
    }

    coordinates(group.toString(), project.name, semver.toString())

    pom {
        name = 'Ceres'
        description = 'A simple serialization library.'
        url = 'https://github.com/fnuecke/ceres'
        licenses {
            license {
                name = 'MIT License'
                url = 'https://github.com/fnuecke/ceres/blob/main/LICENSE'
            }
        }
        developers {
            developer {
                id = 'fnuecke'
                name = 'Florian Nücke'
            }
        }
        scm {
            connection = 'scm:git:https://github.com/fnuecke/ceres.git'
            developerConnection = 'scm:git:ssh://git@github.com/fnuecke/ceres.git'
            url = 'https://github.com/fnuecke/ceres'
        }
    }
}

test {
    useJUnitPlatform()
    systemProperty 'li.cil.ceres.disableCodeGen', 'false'
}

tasks.register('testReflection', Test) {
    description = 'reflection-based serializer tests'
    group = 'verification'

    useJUnitPlatform()
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath
    systemProperty 'li.cil.ceres.disableCodeGen', 'true'
}

check.dependsOn tasks.named('testReflection')
